services:
  front:
    build: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  api:
    build: ./server
    volumes:
      - ./server/src:/app/src
    ports:
      - 4000:4000
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: changemeinprodplease

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080